### ISSUE TITLE
Git commit command needs to be checked

### ISSUE THREAD

**Issue by alphaX86** [ishandeveloper/Coursify-hacktoberfest#96]
Hello there! I gone through the README file and noticed the git commit.

I know -am stages current files but not all files

So I made a pull request regarding this, so look and review it. :)

**Comment by alphaX86** [comment]
Pull request is #40

**Comment by ishandeveloper** [comment]
Hey @alphaX86. Thank you for taking out the time to create this issue and also making a PR for it.

Actually I added that just to ensure that other first-time contributors only commit the existing `data.js` file, if all of them start to use `git add .` . That might cause un-necessary conflicts, and some people might commit files generated by their IDE or something else.

That's why I don't think there's a need of explicitly using `git add .` If you disagree, then please write a comment, and I'll reopen this issue.

Thanks for your contribution. 
### Happy Hacking ! 🎊

**Comment by alphaX86** [comment]
Understood dude! 👍
